mode: "kubernetes"

server:
  name: order-clusterip
  port: 8003

kafka:
  broker_address: "broker:9092"

inventory_service:
  url: "inventory-clusterip:8002"

postgres:
  user: FROM_K8S
  password: FROM_K8S
  host: FROM_K8S
  port: 5432
  db: FROM_K8S

hashicorp_consul:
  port: 8500
  address: consul
