apiVersion: v1
kind: Service
metadata:
  name: authentication-clusterip
  namespace: inventory-management-system
spec:
  type: ClusterIP
  ports:
    - targetPort: 50051
      port: 50051
  selector:
    ims: authentication
