apiVersion: v1
kind: Service
metadata:
  name: authentication-clusterip
  namespace: inventory-management-system
spec:
  type: ClusterIP
  ports:
    - targetPort: 8001
      port: 8001
  selector:
    ims: authentication
