apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: inventory-management-system
spec:
  replicas: 4
  selector:
    matchLabels:
      ims: inventory
  template:
    metadata:
      labels:
        ims: inventory
    spec:
      containers:
        - name: inventory
          image: localhost:5050/ims-inventory:latest
          ports:
            - containerPort: 8002
          env:
            - name: MODE
              value: staging
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: inventory-configmap
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: inventory-configmap
                  key: MYSQL_DATABASE
          readinessProbe:
            grpc:
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            grpc:
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
