apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ims-ingress-resource
  namespace: inventory-management-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localhost # Docker Desktop (Kubernetes)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-clusterip
                port:
                  number: 80
