apiVersion: v1
kind: PersistentVolume
metadata:
  name: ims-pv-inventory
  namespace: inventory-management-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  # manually creating PV to match the StorageClass, ensures that this PV is considered for
  # PVCs that request this StorageClass
  storageClassName: ims-storage-class
  # for dev, mounting a directory from local computer's filesystem on Node into Pod
  hostPath:
    path: /Users/leonlow/persistent_volume/inventory-mysql
  # keeps the PV around for manual cleanup if the PVC is deleted
  persistentVolumeReclaimPolicy: Retain

  # # for prod
  # awsElasticBlockStore:
  #   volumeID: <volume_id> # input volume id after creating EBS
  #   fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ims-pv-order
  namespace: inventory-management-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  storageClassName: ims-storage-class
  hostPath:
    path: /Users/leonlow/persistent_volume/order-postgres
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ims-pv-authentication
  namespace: inventory-management-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  storageClassName: ims-storage-class
  hostPath:
    path: /Users/leonlow/persistent_volume/authentication-postgres
  persistentVolumeReclaimPolicy: Retain
