apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: inventory-management-system
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0LXBhc3N3b3Jk # base64 encoded 'secret-password'
  MYSQL_USER: aW52ZW50b3J5LW15c3Fs # base64 encoded 'inventory-mysql'
  MYSQL_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'

  # base64 encoded 'inventory-headless-service'
  MYSQL_HOST: aW52ZW50b3J5LWhlYWRsZXNzLXNlcnZpY2U=
