apiVersion: v1
kind: Secret
metadata:
  name: authentication-secret
  namespace: inventory-management-system
type: Opaque
data:
  POSTGRES_USER: YXV0aGVudGljYXRpb24tcG9zdGdyZXM= # base64 encoded 'authentication-postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'

  # base64 encoded 'authentication-headless-service'
  POSTGRES_HOST: YXV0aGVudGljYXRpb24taGVhZGxlc3Mtc2VydmljZQ==
