apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: inventory-management-system
type: Opaque
data:
  POSTGRES_USER: b3JkZXItcG9zdGdyZXM= # base64 encoded 'order-postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'

  # base64 encoded 'order-headless-service'
  POSTGRES_HOST: b3JkZXItaGVhZGxlc3Mtc2VydmljZQ==
