version: '3.8' # Or another supported version
services:
  api-gateway:
    image: '<AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/ims-repository:api-gateway-latest'
    ports:
      - '80:80'
    environment:
      MODE: production
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - authentication_service
    networks:
      - ims-network
  authentication-service:
    image: '<AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/ims-repository:authentication-service-latest'
    ports:
      - '50051:50051'
    environment:
      MODE: production
      POSTGRES_USER: authentication_postgres
      POSTGRES_PASSWORD: FROM_ENV
      POSTGRES_HOST: FROM_ENV
      POSTGRES_PORT: 5432
      POSTGRES_DB: imsdb
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - ims-network
  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - '8500:8500'
      - '8600:8600/udp'

networks:
  ims-network:
    driver: bridge
