mode: "docker"

auth_jwt_token:
  name: "ims-auth-token"
  secret: 493TKVrB0r5vY0hqU3OI28iDQJKhWDkR37OXtgSn1tife3z
  max_age: 3600
  domain: "localhost"
  secure: false
  http_only: true
  path: "/"

server:
  url: "api-gateway:80"
  port: 80

auth_service:
  name: FROM_ENV

inventory_service:
  name: inventory-service

order_service:
  name: order-service

hashicorp_consul:
  port: 8500
  address: host.docker.internal

redis_server:
  port: 6379
  address: host.docker.internal
  password: password
  database_index: 0

rate_limiting:
  bucket_lock_expiration: 5 # in seconds
  distributed_locks:
    write: "write"
    read: "read"
    global: "global"

admin_whitelisted_ips:
  - "127.0.0.1"
  - "10.0.0.1"
  - "192.168.65.1"
