mode: 'docker'

auth_jwt_token:
  name: 'ims-auth-token'
  secret: 493TKVrB0r5vY0hqU3OI28iDQJKhWDkR37OXtgSn1tife3z
  max_age: 3600
  domain: 'localhost'
  secure: false
  http_only: true
  path: '/'

server:
  url: 'api-gateway:80'
  port: 80

auth_service:
  name: authentication-clusterip

inventory_service:
  name: inventory-clusterip

order_service:
  name: order-clusterip

hashicorp_consul:
  port: 8500
  address: consul
