mode: "docker"

server:
  url: "api-gateway:80"
  port: 80

jwt:
  secret: 493TKVrB0r5vY0hqU3OI28iDQJKhWDkR37OXtgSn1tife3zuDYdjwnZmzle4rLHRyxH3bRD0l3tyt6zPVOhgBD8NBkMKjgbeIelP+I+8mUuLfjjJZO56oJPflte43sYO6FJm6H9UtR1etzgYAweiaUkWKmonL7X/6XtS7Czr+Q2fX51oGT1QCsbD6I5L92xmTDH7chhFw7aWoIt+NXAZRQrrXE8GiogK+W53Nll3gBNJ/TBjbbrIyIyUBv6nKk/DeDBYhxPQ89WL4qun6uB9pBwT6q5eDfPeOCXUR5C616ulgnOqqv4cNo5Ndy3tVEXwFWiVeUCKB1WbOCPuF0iazQ==

auth_service:
  url: "authentication-clusterip:8001"

inventory_service:
  url: "inventory-clusterip:8002"

order_service:
  url: "order-clusterip:8003"
