CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT                     NOT NULL,
    hashed_password TEXT                     NOT NULL,
    first_name      TEXT                     NOT NULL,
    last_name       TEXT                     NOT NULL,
    active          BOOLEAN                  NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), 
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS admin_users (
    user_id         BIGINT                   NOT NULL REFERENCES users(id),
    active          BOOLEAN                  NOT NULL DEFAULT TRUE,     
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), 
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_admin_users_user_id ON admin_users(user_id);
