mode: "development"

server:
  name: "localhost"
  port: 8002

kafka:
  broker_address: "localhost:9092"

mysql:
  user: inventory-mysql
  password: password
  host: localhost
  port: 3306
  database: imsdb
