mode: "docker"

server:
  name: authentication-service
  port: 8001

jwt:
  secret_key: 493TKVrB0r5vY0hqU3OI28iDQJKhWDkR37OXtgSn1tife3z
  expiry: 15 # in minutes

postgres:
  user: authentication-postgres
  password: password
  host: authentication-postgres
  port: 5432
  db: imsdb

hashicorp_consul:
  port: 8500
  address: host.docker.internal
